// Generated by Wrangler on Mon Aug 12 2024 00:01:20 GMT+0200 (South Africa Standard Time)
// by running `wrangler types --env-interface CloudflareBindings`

export interface CloudflareBindings {
	MY_KV: KVNamespace;
	ASSETS: any;
	SEARCH_CACHE: KVNamespace;
	METADATA_KV: KVNamespace;
	DB: D1Database;
	AI: Ai;
	MY_NAME: string;
	CLOUDFLARE_API_KEY: "PwfJor56sIf_CrWSk09eOT3Np9fla4xU8WSrWYrz";
	CLOUDFLARE_ACCOUNT_ID: "86e2b8822cebf8584cf942edb3103fae";
}
